### ISSUE TITLE
Please update your license and copyright

### ISSUE THREAD

**Issue by olssonm** [russoedu/colorvalidator#2]
Howdy! Seems like you have been influenced by one of my readme- and license-files. However, you seem to have forgotten to **remove my name from them**. 

Both your readme.md and licence.md mentions me by name and contains a link to my website – I however of course does not have anything to do with this package =)

**Comment by russoedu** [comment]
Sorry about that! Yes, I probably used some of your packs as the base.

I already removed them.

Thanks for letting me know.
